# Generated by Django 4.2.1 on 2023-11-27 02:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('suffix_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Suffix')),
                ('image', models.ImageField(default='profile_pict/image.jpg', upload_to=users.models.image_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_provider', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
